### ISSUE TITLE
talos_data has a dependency to Gazebo set to required plus informations to be used outside the gazebo use_case

### ISSUE THREAD

**Issue by olivier-stasse** [stack-of-tasks/talos_data#3]
The dependency is due to the gazebo plugin suppose to simulate the spring in the hip.
This has been set to required in
 https://github.com/stack-of-tasks/talos-data/blob/5514692d4b81c22c61ad82a995cf267bf058929a/CMakeLists.txt#L26
Unfortunately they are additional information specifically for the walking pattern generator which are set here:
https://github.com/stack-of-tasks/talos-data/blob/master/srdf/talos_wpg.srdf

Due to this jrl-walkgen has a dependency to talos-data and then to gazebo. The later is not welcome when using jrl-walkgen. The problem is that right now it is difficult programmatically to cut the dependency to gazebo. 

They are several other solutions:

- [ ] Move the data related to the wpg in a different place (I would prefer to avoid another package) example-robot-data should stay clean IMHO
- [ ] Move the gazebo plugin to another package talos_data_gazebo (for the same reason I do not think this is worth it)
- [ ] Make Gazebo optional when needed at compilation, and installed system-wide for the binary distribution.

I feel that the third solution is better for the long term.

Happy to discuss simple and fast solution.

**Comment by nim65s** [comment]
For the first solution, if we move talos_wpg.srdf (that is required by jrl-walkgen) directly into jrl-walkgen, would that fix your use case ?

**Comment by nim65s** [comment]
fixed by
- https://github.com/stack-of-tasks/talos-data/commit/b29390b8479d345721280f7f4467f57ffd31a5f9
- https://github.com/stack-of-tasks/jrl-walkgen/commit/e07fa3f5a059fd28aa08d0c38eff6ad9bcea3f7c
